# Generated by Django 5.1.3 on 2024-11-08 19:10

import django.utils.timezone
import homeflix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('protagonist', models.CharField(max_length=100, verbose_name='Protagonista')),
                ('protagonist_image', models.ImageField(blank=True, null=True, upload_to=homeflix.models.protagonist_image_path, verbose_name='Foto do Protagonista')),
                ('movie_file', models.FileField(upload_to=homeflix.models.movie_upload_path, verbose_name='Arquivo do Filme')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Upload')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-upload_date'],
            },
        ),
    ]
