# Generated by Django 5.1.3 on 2024-11-08 20:42

import django.db.models.deletion
import homeflix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homeflix.models.protagonist_image_path, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Protagonista',
                'verbose_name_plural': 'Protagonistas',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='protagonist_image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='protagonist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='homeflix.protagonist', verbose_name='Protagonista'),
        ),
    ]
