# Generated by Django 5.1.3 on 2024-11-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeflix', '0002_protagonist_remove_movie_protagonist_image_and_more'),
    ]

    operations = [
    ]
